# Generated by Django 5.2.4 on 2025-08-10 07:25

from django.db import migrations

def create_admin_user(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='Thanu',
            email='admin@example.com',
            password='Thanu123'
        )

class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),  # make sure this matches your last migration
    ]

    operations = [
        migrations.RunPython(create_admin_user),
    ]
